version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
