apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flower_shop
  template:
    metadata:
      labels:
        app: flower_shop
    spec:
      containers:
      - name: capstone
        image: satishosk/capstone:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_URI
        - name: PORT
          value: "8000"
